"""empty message

Revision ID: 3b1157d82824
Revises: b10aef4a97c3
Create Date: 2020-06-24 17:13:17.075551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b1157d82824'
down_revision = 'b10aef4a97c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reading', sa.Column('data_type', sa.Integer(), nullable=False))
    op.drop_constraint(None, 'reading', type_='foreignkey')
    op.drop_column('reading', 'sensor_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reading', sa.Column('sensor_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'reading', 'sensor', ['sensor_id'], ['id'])
    op.drop_column('reading', 'data_type')
    # ### end Alembic commands ###
