"""new_model

Revision ID: d35f26d1a422
Revises: 
Create Date: 2020-08-13 23:14:07.344997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd35f26d1a422'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actuator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('state_current', sa.Boolean(), nullable=False),
    sa.Column('ip', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actuator_ip'), 'actuator', ['ip'], unique=True)
    op.create_index(op.f('ix_actuator_name'), 'actuator', ['name'], unique=True)
    op.create_table('controller_led',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('gpio_red', sa.Integer(), nullable=False),
    sa.Column('gpio_green', sa.Integer(), nullable=False),
    sa.Column('gpio_blue', sa.Integer(), nullable=False),
    sa.Column('state_current', sa.Boolean(), nullable=False),
    sa.Column('state_colorshift', sa.Boolean(), nullable=False),
    sa.Column('state_red', sa.Integer(), nullable=False),
    sa.Column('state_green', sa.Integer(), nullable=False),
    sa.Column('state_blue', sa.Integer(), nullable=False),
    sa.Column('state_brightness', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_controller_led_name'), 'controller_led', ['name'], unique=True)
    op.create_table('reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('data_reading', sa.Float(), nullable=False),
    sa.Column('data_type', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reading_timestamp'), 'reading', ['timestamp'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Time(), nullable=False),
    sa.Column('actuator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actuator_id'], ['actuator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_timestamp'), 'schedule', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_timestamp'), table_name='schedule')
    op.drop_table('schedule')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_reading_timestamp'), table_name='reading')
    op.drop_table('reading')
    op.drop_index(op.f('ix_controller_led_name'), table_name='controller_led')
    op.drop_table('controller_led')
    op.drop_index(op.f('ix_actuator_name'), table_name='actuator')
    op.drop_index(op.f('ix_actuator_ip'), table_name='actuator')
    op.drop_table('actuator')
    # ### end Alembic commands ###
